version: "3.4"
# Create a Jenkins container
#  docker pull jenkins/jenkins:lts
#  docker run -p 8080:8080 -p 50000:50000 -d -v jenkins_home:/var/jenkins_home --name jenkins jenkins/jenkins:lts
#  docker logs jenkins

services:
  jenkins:
    container_name: jenkins
    #command:  "tail -F anything"
    image: jenkins/jenkins:lts
    volumes:
      - C:\Users\ThinkPad\.jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
   # user: root